[tool.poetry]
name = "zscaler-sdk-python"
version = "1.0.0"
description = "Framework for interacting with Zscaler Cloud via API"
authors = ["Zscaler Technology Alliances <zscaler-partner-labs@z-bd.com>"]
license = "MIT"
keywords = ["zscaler", "zpa", "zia", "zscaler-sdk-python"]
readme = "README.md"
documentation = "https://zscaler-sdk-python.readthedocs.io/"
homepage = "https://github.com/zscaler/zscaler-sdk-python"
repository = "https://github.com/zscaler/zscaler-sdk-python"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries :: Python Modules", ]
include = [
    "LICENSE",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/zscaler/zscaler-sdk-python/issues"

[tool.poetry.dependencies]
python = "^3.7"
restfly = "1.4.7"
python-box = "7.0.0"

[tool.poetry.dev-dependencies]
python = "^3.7"
restfly = "1.4.7"
python-box = "7.0.0"
sphinx = "6.1.3"
furo = "2022.12.7"
pytest = "7.2.1"
requests = "2.28.2"
pre-commit = "3.0.4"
responses = "0.22.0"
toml = "0.10.2"
black = {version = "^19.10b0", python = "^3.6"}
flake8-eradicate = {version = "^0.2.4", python = "^3.6"}
flake8-bugbear = {version = "^20.1.2", python = "^3.6"}
flake8 = "^3.7.9"
flake8-logging-format = "^0.6.0"
flake8-pep3101 = "^1.3.0"
flake8-builtins = "^1.4.2"
flake8-comprehensions = {version = "^3.1.4", python = "^3.5"}
flake8-string-format = "^0.2.3"
flake8-mutable = "^1.2.0"
flake8-pytest = "^1.3"
flake8-mock = "^0.3"
flake8-docstrings = "^1.5.0"
flake8-variables-names = "^0.0.3"
pep8-naming = "^0.9.1"
poetry2setup = {version = "^1.1.0", python = ">=3.6"}
fissix = {version = "^19.2b1", python = "^3.6"}
sphinx = {version = "^2.3.1", python = "^3.5"}
pytest-cov = {version = "^2.8.1", python = "^3.5"}
sphinx_rtd_theme = {version = "^0.4.3", python = "^3.5"}
sphinx-autobuild = {version = "^0.7.1", python = "^3.5"}
bandit = "^1.6.2"
isort = "^4.3.21"
m2r = "^0.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 127

[tool.pylint.'MESSAGES CONTROL']
disable=[
    "format",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-many-public-methods",
    "anomalous-backslash-in-string",
    "import-error",
    "redefined-outer-name",
]

[tool.pylint.'FORMAT']
max-line-length = 127

[tool.isort]
profile = "black"
